const creativeDirection = brief => [
  `Giữ ${brief.briefPatch.brand} là thương hiệu chính.`,
  'Bố cục rõ, ít chữ, hình ảnh nổi bật và phù hợp nhóm khách hàng trong brief.',
  'Không tự thêm giá, ưu đãi hoặc claim chưa có trong brief.',
].join(' ')

export function buildAutopilotLiveSteps(brief, options = {}) {
  const creativeSource = options.creativeSource
    || (Math.random() < 0.5 ? 'upload' : 'ai_generate')
  const usesUpload = creativeSource === 'upload'
  const creativeSourceSteps = usesUpload ? [
    {
      type: 'CLICK_EL',
      target: '[data-demo="autopilot-source-upload"]',
      tooltip: {
        target: '[data-demo="autopilot-source-upload"]',
        position: 'bottom',
        title: 'Dùng bộ creative có sẵn',
        text: 'Scenario này đã có một bộ creative được chuẩn bị trước theo nhiều định dạng. Walkthrough sẽ đưa toàn bộ bộ ảnh vào bước Creative để phân tích và dùng khi gán placement.',
      },
    },
    {
      type: 'INJECT_DEMO_CREATIVES',
      briefId: brief.id,
    },
    {
      type: 'TOOLTIP',
      target: '[data-demo="autopilot-source-upload"]',
      position: 'bottom',
      title: 'Creative tải lên đã sẵn sàng',
      text: 'Các file của scenario đã được nạp vào workspace tạm. Khi Autopilot đến checkpoint Creative, walkthrough sẽ mở editor, chờ phân tích xong và lưu chúng vào campaign truth.',
    },
  ] : [
    {
      type: 'CLICK_EL',
      target: '[data-demo="autopilot-source-ai"]',
      tooltip: {
        target: '[data-demo="autopilot-source-ai"]',
        position: 'bottom',
        title: 'Để Agent chuẩn bị creative',
        text: 'Agent sẽ tạo draft theo đúng các định dạng placement, sau đó kiểm tra nội dung và chỉ yêu cầu con người duyệt khi có rủi ro hoặc độ tin cậy thấp.',
      },
    },
    {
      type: 'TYPE_INPUT',
      target: '[data-demo="autopilot-creative-direction"]',
      inputText: creativeDirection(brief),
      charDelay: 8,
      autoAdvance: true,
    },
  ]

  return [
    {
      type: 'TOOLTIP',
      target: '#chat-input',
      position: 'top',
      title: 'Bắt đầu bằng một scenario brief thật',
      text: `Walkthrough chọn scenario **${brief.briefPatch.brand}** từ danh sách brief mẫu. Brief sẽ được Agent chuẩn hóa và lưu vào campaign workspace trước khi Autopilot chạy.`,
    },
    {
      type: 'TYPE_AND_SEND',
      text: brief.chatMessage,
      tooltip: {
        target: '#chat-input',
        position: 'top',
        title: 'Đang gửi brief cho Agent',
        text: 'Agent đang hiểu yêu cầu, chuẩn hóa dữ liệu và tạo đề xuất cập nhật Brief.',
      },
    },
    {
      type: 'WAIT_FOR_RESPONSE',
      tooltip: {
        target: '[data-demo="chat-thread"]',
        position: 'right',
        title: 'Đang chuẩn hóa brief',
        text: 'Walkthrough chờ Agent hiểu và chuẩn hóa nội dung trước khi tiếp tục.',
      },
    },
    {
      type: 'HIGHLIGHT_MSG',
      position: 'right',
      title: 'Review đề xuất trước khi chạy',
      text: 'Đây là Brief mà Agent hiểu từ nội dung vừa gửi. Walkthrough sẽ áp dụng đề xuất này vào workspace; run Autopilot vẫn chưa bắt đầu.',
    },
    {
      type: 'APPLY_AUTOPILOT_BRIEF',
      target: '[data-demo="workspace-proposal-confirm"][data-workspace-field="brief"]',
      tooltip: {
        target: '[data-demo="chat-thread"]',
        position: 'right',
        title: 'Áp dụng Brief vào campaign truth',
        text: 'Đang xác nhận proposal và đợi backend ghi Brief vào canonical workspace.',
      },
    },
    {
      type: 'WAIT_FOR_SELECTOR',
      target: '[data-demo="autopilot-brief-status"][data-ready="true"]',
      timeout: 30000,
      title: 'Đang đồng bộ Brief',
      text: 'Autopilot chỉ mở run khi Brief đã được lưu, hợp lệ và không còn proposal chờ xử lý.',
    },
    ...creativeSourceSteps,
    {
      type: 'TOOLTIP',
      target: '[data-demo="autopilot-policy-review_every_stage"]',
      position: 'bottom',
      title: 'Duyệt từng giai đoạn',
      text: 'Autopilot dừng thường xuyên để bạn kiểm tra từng nhóm quyết định. Phù hợp khi campaign nhạy cảm hoặc cần kiểm soát tối đa, nhưng sẽ cần nhiều thao tác hơn.',
    },
    {
      type: 'TOOLTIP',
      target: '[data-demo="autopilot-policy-critical_only"]',
      position: 'bottom',
      title: 'Duyệt các bước quan trọng · Khuyến nghị',
      text: 'Đây là lựa chọn cân bằng cho quy trình bán tự động: Agent chủ động xử lý phần thường quy và dừng tại năm quyết định quan trọng để có **human-in-the-loop**.',
    },
    {
      type: 'TOOLTIP',
      target: '[data-demo="autopilot-policy-auto_build_draft"]',
      position: 'bottom',
      title: 'Tự xây dựng bản nháp',
      text: 'Agent đi liền mạch để hoàn thiện campaign draft và chỉ dừng trước launch hoặc khi gặp rủi ro bắt buộc phải review.',
    },
    {
      type: 'CLICK_EL',
      target: '[data-demo="autopilot-policy-critical_only"]',
      tooltip: {
        target: '[data-demo="autopilot-policy-critical_only"]',
        position: 'bottom',
        title: 'Giữ quyền kiểm soát ở các bước quan trọng',
        text: 'Walkthrough chọn chế độ khuyến nghị: dừng tại **Tìm audience → Thiết lập targeting → Đề xuất placement sơ bộ → Gán creative → Duyệt launch**. Creative có rủi ro vẫn luôn dừng riêng để review.',
      },
    },
    {
      type: 'TOOLTIP',
      target: '[data-demo="autopilot-start-run"]',
      position: 'top',
      title: 'Khởi tạo durable run',
      text: 'Sau khi bấm, backend tạo một plan có task, dependency, evidence và idempotency riêng. Walkthrough sẽ chờ từng checkpoint thật thay vì chạy theo timer cố định.',
    },
    {
      type: 'CLICK_EL',
      target: '[data-demo="autopilot-start-run"]',
      tooltip: {
        target: '[data-demo="autopilot-start-run"]',
        position: 'top',
        title: 'Autopilot đang lập kế hoạch',
        text: 'Đang tạo run và thực thi các bước đầu tiên.',
      },
    },
    {
      type: 'WAIT_FOR_SELECTOR',
      target: '[data-demo="autopilot-plan-details"]',
      timeout: 30000,
      title: 'Đang dựng kế hoạch thực thi',
      text: 'Walkthrough chờ task graph xuất hiện để giới thiệu cách đọc Autopilot trước khi xử lý checkpoint đầu tiên.',
    },
    {
      type: 'TOOLTIP',
      target: '[data-demo="autopilot-execution-plan"]',
      position: 'top',
      title: 'Năm giai đoạn của một Autopilot run',
      text: 'Thanh tiến độ gom toàn bộ run thành **Brief & chiến lược → Audience & targeting → Placement & creative → Dự báo & an toàn → Launch & hoàn tất**. Màu sắc cho biết phần nào đang chạy, đã xong hoặc đang chờ bạn.',
    },
    {
      type: 'CLICK_EL',
      target: '[data-demo="autopilot-plan-details"] > summary',
      tooltip: {
        target: '[data-demo="autopilot-plan-details"]',
        position: 'top',
        title: 'Mở toàn bộ 18 bước',
        text: 'Đang mở task graph theo đúng thứ tự thực thi để bạn thấy Autopilot không phải một thao tác “chạy mù”.',
      },
    },
    {
      type: 'TOOLTIP',
      target: '[data-demo="autopilot-plan-details"]',
      position: 'top',
      title: 'Task graph, dependency và trạng thái',
      text: 'Danh sách này cho biết từng bước đang chờ dependency, đang chạy, đã hoàn tất hay cần review. Khi bạn sửa một artifact, chỉ các task phụ thuộc mới được tính lại.',
    },
    {
      type: 'WAIT_FOR_SELECTOR',
      target: '[data-demo="autopilot-strategy-calculation"]',
      timeout: 90000,
      title: 'Đang chuẩn bị các phương án chiến lược',
      text: 'Agent đang chuyển brief thành các phương án phân bổ có thể so sánh trước khi đi vào review.',
    },
    {
      type: 'TOOLTIP',
      target: '[data-demo="autopilot-strategy-simulator"]',
      position: 'top',
      title: 'So sánh chiến lược trước khi triển khai',
      text: 'Ba phương án thể hiện các trade-off khác nhau về reach, tần suất, CPM và rủi ro. Phương án đang chọn là đầu vào cho các bước audience, placement và forecast tiếp theo.',
    },
    {
      type: 'CLICK_EL',
      target: '[data-demo="autopilot-strategy-calculation"] > summary',
      tooltip: {
        target: '[data-demo="autopilot-strategy-calculation"]',
        position: 'top',
        title: 'Mở cách tính số liệu',
        text: 'Đang mở đầu vào, công thức impression, reach và phương pháp ước tính phía sau các phương án.',
      },
    },
    {
      type: 'TOOLTIP',
      target: '[data-demo="autopilot-strategy-calculation"]',
      position: 'top',
      title: 'Số liệu có nguồn gốc rõ ràng',
      text: 'Phần này tách **đầu vào đã biết**, **công thức tính** và **giả định lập kế hoạch**. Nhờ vậy bạn có thể đánh giá vì sao một phương án được chọn thay vì chỉ nhìn con số cuối.',
    },
    {
      type: 'CLICK_EL',
      target: '[data-demo="autopilot-technical-details"] > summary',
      tooltip: {
        target: '[data-demo="autopilot-technical-details"]',
        position: 'top',
        title: 'Mở chi tiết kỹ thuật',
        text: 'Đang mở trace, bằng chứng retrieval, guard và idempotency của run.',
      },
    },
    {
      type: 'TOOLTIP',
      target: '[data-demo="autopilot-technical-details"]',
      position: 'top',
      title: 'Bằng chứng để debug và audit',
      text: 'Mỗi task bổ sung evidence vào đây. Phần này giúp đội vận hành kiểm tra dữ liệu đã dùng, guard đã chạy và lần thực thi nào tạo ra artifact hiện tại.',
    },
    {
      type: 'WAIT_FOR_AUTOPILOT_TASK',
      taskKeys: ['retrieve_audience'],
      timeout: 120000,
      title: 'Đang chờ checkpoint Tìm audience',
      text: 'Agent đang dùng brief, catalog và retrieval pipeline để chọn tập audience ban đầu.',
    },
    {
      type: 'TOOLTIP',
      target: '[data-demo="autopilot-review-artifact"][data-autopilot-task="retrieve_audience"]',
      position: 'top',
      title: 'Artifact Audience có bằng chứng',
      text: 'Thẻ này cho biết catalog đã được tìm như thế nào, số ứng viên RAG và các segment cuối cùng. Ta sẽ mở editor và giữ lại ít segment hơn.',
    },
    {
      type: 'CLICK_EL',
      target: '[data-demo="autopilot-edit-retrieve_audience"]',
      tooltip: {
        target: '[data-demo="autopilot-edit-retrieve_audience"]',
        position: 'top',
        title: 'Chỉnh Audience trong cùng run',
        text: 'Editor dùng canonical workspace. Khi lưu, Autopilot chỉ tính lại nhánh phụ thuộc; các artifact không liên quan được giữ nguyên.',
      },
    },
    {
      type: 'WAIT_FOR_SELECTOR',
      target: '[data-demo="autopilot-audience-option"][aria-pressed="true"]',
      timeout: 30000,
      title: 'Đang mở danh sách segment',
      text: 'Walkthrough chờ catalog và lựa chọn hiện tại hiển thị đầy đủ.',
    },
    {
      type: 'TRIM_AUTOPILOT_AUDIENCE',
      keep: 3,
      title: 'Giảm audience xuống 3 segment',
      text: 'Walkthrough đang bỏ bớt các segment cuối danh sách và giữ ba lựa chọn đầu tiên để minh họa quyền chỉnh quyết định của Agent.',
    },
    {
      type: 'TOOLTIP',
      target: '[data-demo="ai-reco-section"]',
      position: 'top',
      title: 'Audience đã được thu gọn',
      text: 'Các card được bỏ chọn ngay trên form thật. Unique reach sẽ được backend tính lại cho tập segment mới.',
    },
    {
      type: 'WAIT_FOR_SELECTOR',
      target: '[data-demo="autopilot-editor-save"]:not(:disabled)',
      timeout: 30000,
      title: 'Đang tính lại unique reach',
      text: 'Nút lưu chỉ mở khi tập audience mới có dữ liệu hợp lệ.',
    },
    {
      type: 'CLICK_EL',
      target: '[data-demo="autopilot-editor-save"]',
      tooltip: {
        target: '[data-demo="autopilot-editor-save"]',
        position: 'top',
        title: 'Lưu Audience và replan',
        text: 'Đang ghi artifact Audience mới. Review đang chờ sẽ được supersede an toàn và run tiếp tục từ dependency phù hợp.',
      },
    },
    {
      type: 'WAIT_FOR_AUTOPILOT_TASK',
      taskKeys: ['derive_targeting'],
      timeout: 120000,
      title: 'Đang chờ checkpoint Thiết lập targeting',
      text: 'Agent đang suy ra targeting từ brief và audience vừa được chỉnh.',
    },
    {
      type: 'TOOLTIP',
      target: '[data-demo="autopilot-review-artifact"][data-autopilot-task="derive_targeting"]',
      position: 'top',
      title: 'Targeting là artifact riêng',
      text: 'Tuổi, giới tính, địa lý và device được lưu độc lập với DMP segments. Vì vậy ta có thể đổi targeting mà không ghi đè Audience.',
    },
    {
      type: 'CLICK_EL',
      target: '[data-demo="autopilot-edit-derive_targeting"]',
      tooltip: {
        target: '[data-demo="autopilot-edit-derive_targeting"]',
        position: 'top',
        title: 'Mở targeting catalog',
        text: 'Walkthrough sẽ thêm lựa chọn hợp lệ từ catalog thay vì tự tạo chuỗi targeting.',
      },
    },
    {
      type: 'WAIT_FOR_SELECTOR',
      target: '[data-demo="autopilot-targeting-option"][data-targeting-dimension="age"]',
      timeout: 30000,
      title: 'Đang tải targeting options',
      text: 'Chờ các giá trị hợp lệ từ targeting catalog.',
    },
    {
      type: 'CHANGE_AUTOPILOT_TARGETING',
      dimensions: ['age', 'deviceOS'],
      title: 'Thử một cấu hình targeting khác',
      text: 'Walkthrough đang thêm một nhóm tuổi và một hệ điều hành chưa được chọn. Đây là thay đổi thật trên form và vẫn bị giới hạn bởi catalog.',
    },
    {
      type: 'TOOLTIP',
      target: '[data-demo="targeting-panel-toggle"]',
      position: 'top',
      title: 'Targeting đã thay đổi',
      text: 'Badge tổng số lựa chọn đã cập nhật. Khi lưu, Autopilot sẽ đánh dấu đúng các task downstream cần tính lại.',
    },
    {
      type: 'WAIT_FOR_SELECTOR',
      target: '[data-demo="autopilot-editor-save"]:not(:disabled)',
      timeout: 30000,
      title: 'Đang kiểm tra targeting',
      text: 'Chỉ các lựa chọn hợp lệ trong catalog mới có thể được lưu.',
    },
    {
      type: 'CLICK_EL',
      target: '[data-demo="autopilot-editor-save"]',
      tooltip: {
        target: '[data-demo="autopilot-editor-save"]',
        position: 'top',
        title: 'Lưu targeting và tiếp tục run',
        text: 'Đang commit targeting mới vào canonical workspace.',
      },
    },
    {
      type: 'WAIT_FOR_AUTOPILOT_TASK',
      taskKeys: ['plan_placement_intent'],
      timeout: 120000,
      title: 'Đang chờ Đề xuất placement sơ bộ',
      text: 'Autopilot đang kiểm tra inventory, conflict và xếp hạng shortlist trước khi biết creative cuối.',
    },
    {
      type: 'TOOLTIP',
      target: '[data-demo="autopilot-review-artifact"][data-autopilot-task="plan_placement_intent"]',
      position: 'top',
      title: 'Shortlist placement trước creative',
      text: 'Đây là đề xuất sơ bộ dựa trên inventory. Ta sẽ bỏ bớt cho đến khi còn đúng **2 placement**, sau đó creative format plan sẽ được tính từ hai lựa chọn này.',
    },
    {
      type: 'TRIM_AUTOPILOT_PLACEMENTS',
      keep: 2,
      title: 'Giữ lại đúng 2 placement',
      text: 'Walkthrough đang bỏ chọn từng placement trên artifact review. Thay đổi chỉ được lưu khi duyệt checkpoint.',
    },
    {
      type: 'TOOLTIP',
      target: '[data-demo="autopilot-review-artifact"][data-autopilot-task="plan_placement_intent"]',
      position: 'top',
      title: 'Hai placement đã được chọn',
      text: 'Format plan, creative preparation và forecast downstream sẽ dùng đúng shortlist này.',
    },
    {
      type: 'CLICK_EL',
      target: '[data-demo="autopilot-review-approve"][data-autopilot-task="plan_placement_intent"]',
      tooltip: {
        target: '[data-demo="autopilot-review-approve"]',
        position: 'top',
        title: usesUpload ? 'Duyệt shortlist và chuẩn bị creative' : 'Duyệt shortlist và tạo creative',
        text: usesUpload
          ? 'Autopilot đang lưu 2 placement, lập format plan và chuyển sang bộ creative tải lên để phân tích.'
          : 'Autopilot đang lưu 2 placement, lập format plan, chuẩn bị creative và kiểm tra chất lượng. Bước này có thể mất vài phút.',
      },
    },
    ...(usesUpload ? [
      {
        type: 'WAIT_FOR_AUTOPILOT_TASK',
        taskKeys: ['prepare_creatives'],
        timeout: 120000,
        title: 'Đang chờ bộ creative tải lên',
        text: 'Autopilot đã lập xong format plan và đang dừng để bạn kiểm tra bộ file của scenario.',
      },
      {
        type: 'TOOLTIP',
        target: '[data-demo="autopilot-review-artifact"][data-autopilot-task="prepare_creatives"]',
        position: 'top',
        title: 'Checkpoint Creative đầu vào',
        text: 'Ở nhánh Upload, Autopilot không tự thay thế tài sản đã có. Walkthrough sẽ mở editor thật, đưa toàn bộ creative chuẩn bị trước vào và chờ phân tích.',
      },
      {
        type: 'CLICK_EL',
        target: '[data-demo="autopilot-edit-prepare_creatives"]',
        tooltip: {
          target: '[data-demo="autopilot-edit-prepare_creatives"]',
          position: 'top',
          title: 'Mở Creative editor',
          text: 'Đang mở bộ creative của scenario và các format mà hai placement đã chọn cần sử dụng.',
        },
      },
      {
        type: 'WAIT_FOR_SELECTOR',
        target: '[data-demo="creative-review-state"]',
        timeout: 30000,
        title: 'Đang nạp creative đã chuẩn bị',
        text: 'Walkthrough chờ toàn bộ file xuất hiện trong editor trước khi tiếp tục.',
      },
      {
        type: 'TOOLTIP',
        target: '#creative-drop-zone',
        position: 'top',
        title: 'Toàn bộ creative của scenario đã được đưa vào',
        text: 'Giống walkthrough Copilot, bộ ảnh chuẩn bị trước được tải cùng lúc. Tiếp theo walkthrough sẽ bắt đầu phân tích, nhưng vẫn giữ editor mở để bạn đọc kết quả.',
      },
      {
        type: 'CLICK_EL',
        target: '[data-demo="autopilot-editor-save"]',
        tooltip: {
          target: '[data-demo="autopilot-editor-save"]',
          position: 'top',
          title: 'Bắt đầu phân tích creative',
          text: 'Đang upload các file và kiểm tra kích thước, nội dung, thương hiệu cùng độ phù hợp. Editor sẽ không tự đóng sau khi kết quả xuất hiện.',
        },
      },
      {
        type: 'WAIT_FOR_CREATIVE_REVIEW',
        reviewStates: ['ready', 'blocked'],
        timeout: 180000,
        title: 'Đang phân tích bộ creative',
        text: 'Walkthrough giữ nguyên tại editor cho tới khi mọi file có kết quả cuối để bạn không bị chuyển nhanh qua phần quan trọng này.',
      },
      {
        type: 'TYPE_INPUT',
        target: '#creative-manual-review-reason',
        whenReviewState: 'blocked',
        inputText: 'Đã kiểm tra thủ công nội dung, thương hiệu và chấp nhận sử dụng trong walkthrough Autopilot.',
        charDelay: 10,
        autoAdvance: true,
      },
      {
        type: 'CLICK_EL',
        target: '#creative-manual-review-approve',
        whenReviewState: 'blocked',
        tooltip: {
          target: '#creative-manual-review-approve',
          position: 'top',
          title: 'Ghi nhận duyệt thủ công',
          text: 'Lý do phê duyệt được lưu cùng kết quả phân tích để giữ audit trail.',
        },
      },
      {
        type: 'WAIT_FOR_CREATIVE_REVIEW',
        reviewStates: ['ready'],
        timeout: 60000,
        title: 'Đang chờ toàn bộ creative sẵn sàng',
        text: 'Mọi file phải được tự động chấp thuận hoặc có phê duyệt thủ công hợp lệ.',
      },
      {
        type: 'TOOLTIP',
        target: '[data-demo="creative-review-state"]',
        position: 'top',
        title: 'Creative đã sẵn sàng để lưu',
        text: 'Bạn có thể đọc trạng thái từng file trước khi tiếp tục. Walkthrough chỉ lưu khi tất cả creative đã qua hàng rào review.',
      },
      {
        type: 'CLICK_EL',
        target: '[data-demo="autopilot-editor-save"]',
        tooltip: {
          target: '[data-demo="autopilot-editor-save"]',
          position: 'top',
          title: 'Lưu bộ creative tải lên',
          text: 'Đang upload, lưu kết quả phân tích và đưa các file vào campaign truth để Autopilot tiếp tục.',
        },
      },
    ] : [
      {
        type: 'WAIT_FOR_SELECTOR',
        target: '[data-demo="autopilot-creative-plan"]',
        timeout: 180000,
        title: 'Đang chuẩn bị creative theo format plan',
        text: 'Walkthrough giữ phần tiến độ trên màn hình trong khi creative được tạo và kiểm tra.',
      },
      {
        type: 'TOOLTIP',
        target: '[data-demo="autopilot-creative-plan"]',
        position: 'top',
        title: 'Creative đang được chuẩn bị và phân tích',
        text: 'Mỗi format được xử lý theo placement đã chọn, sau đó kiểm tra bố cục, nội dung, thương hiệu và các dấu hiệu rủi ro. Bạn chủ động bấm tiếp sau khi đã đọc phần này.',
      },
      {
        type: 'WAIT_FOR_AUTOPILOT_TASK',
        taskKeys: ['analyze_creatives', 'assign_creatives'],
        timeout: 360000,
        title: 'Đang hoàn tất phân tích creative',
        text: 'Nếu có file cần người xem lại, walkthrough sẽ mở nhánh duyệt thủ công. Nếu tất cả đều đạt, nó vẫn dừng ở phần kết quả trước khi sang gán creative.',
      },
      {
        type: 'TOOLTIP',
        target: '[data-demo="autopilot-review-artifact"][data-autopilot-task="analyze_creatives"]',
        whenAutopilotTask: 'analyze_creatives',
        position: 'top',
        title: 'Creative Intelligence yêu cầu review',
        text: 'Ít nhất một ảnh cần con người xác nhận. Walkthrough sẽ mở Creative editor, đọc trạng thái và không bỏ qua hàng rào này.',
      },
      {
        type: 'CLICK_EL',
        target: '[data-demo="autopilot-edit-analyze_creatives"]',
        whenAutopilotTask: 'analyze_creatives',
        tooltip: {
          target: '[data-demo="autopilot-edit-analyze_creatives"]',
          position: 'top',
          title: 'Mở Creative review',
          text: 'Đang mở các ảnh, kết quả phân tích và lý do cần review.',
        },
      },
      {
        type: 'WAIT_FOR_CREATIVE_REVIEW',
        whenAutopilotTask: 'analyze_creatives',
        reviewStates: ['ready', 'blocked'],
        timeout: 120000,
        title: 'Đang đọc kết quả Creative Intelligence',
        text: 'Walkthrough chỉ tiếp tục khi mọi ảnh có kết quả cuối.',
      },
      {
        type: 'TYPE_INPUT',
        target: '#creative-manual-review-reason',
        whenAutopilotTask: 'analyze_creatives',
        whenReviewState: 'blocked',
        inputText: 'Đã kiểm tra thủ công nội dung, thương hiệu và chấp nhận sử dụng trong walkthrough Autopilot.',
        charDelay: 10,
        autoAdvance: true,
      },
      {
        type: 'CLICK_EL',
        target: '#creative-manual-review-approve',
        whenAutopilotTask: 'analyze_creatives',
        whenReviewState: 'blocked',
        tooltip: {
          target: '#creative-manual-review-approve',
          position: 'top',
          title: 'Ghi nhận duyệt thủ công',
          text: 'Lý do phê duyệt được lưu cùng kết quả phân tích, không chỉ thay đổi trạng thái trên giao diện.',
        },
      },
      {
        type: 'WAIT_FOR_CREATIVE_REVIEW',
        whenAutopilotTask: 'analyze_creatives',
        reviewStates: ['ready'],
        timeout: 60000,
        title: 'Đang chờ creative sẵn sàng',
        text: 'Mọi creative phải được tự động chấp thuận hoặc có phê duyệt thủ công hợp lệ.',
      },
      {
        type: 'CLICK_EL',
        target: '[data-demo="autopilot-editor-save"]',
        whenAutopilotTask: 'analyze_creatives',
        tooltip: {
          target: '[data-demo="autopilot-editor-save"]',
          position: 'top',
          title: 'Lưu kết quả và quay lại run',
          text: 'Autopilot sẽ kiểm tra lại nhánh creative trước khi xếp hạng placement cuối.',
        },
      },
    ]),
    {
      type: 'WAIT_FOR_AUTOPILOT_TASK',
      taskKeys: ['assign_creatives'],
      timeout: 240000,
      title: 'Đang chờ checkpoint Gán creative',
      text: 'Agent đang giữ lại placement tương thích và chuẩn bị phân bổ các ảnh đã duyệt.',
    },
    {
      type: 'TOOLTIP',
      target: '[data-demo="autopilot-creative-plan"]',
      position: 'top',
      title: usesUpload ? 'Creative tải lên đã qua phân tích' : 'Creative đã sẵn sàng theo format plan',
      text: 'Mỗi asset hiển thị format, kích thước và số placement có thể phủ. Walkthrough dừng tại đây để bạn đọc kết quả trước khi mở bước gán creative.',
    },
    {
      type: 'CLICK_EL',
      target: '[data-demo="autopilot-edit-assign_creatives"]',
      tooltip: {
        target: '[data-demo="autopilot-edit-assign_creatives"]',
        position: 'top',
        title: 'Mở creative assignment',
        text: 'Ta sẽ để bộ chọn chấm điểm lại và gán creative đã duyệt phù hợp nhất cho từng placement.',
      },
    },
    {
      type: 'WAIT_FOR_SELECTOR',
      target: '[data-demo="autopilot-creative-assignment-editor"]',
      timeout: 30000,
      title: 'Đang mở ma trận creative × placement',
      text: 'Mỗi hàng là một placement; mỗi lựa chọn là creative đã có verdict.',
    },
    {
      type: 'TOOLTIP',
      target: '[data-demo="auto-assign-btn"]',
      position: 'top',
      title: 'Creative selection có giải thích',
      text: 'Nút này chọn file đã duyệt có điểm tương thích tốt nhất cho từng placement dựa trên format và tỷ lệ. Người vận hành vẫn có thể thay từng lựa chọn.',
    },
    {
      type: 'CLICK_EL',
      target: '[data-demo="auto-assign-btn"]',
      tooltip: {
        target: '[data-demo="auto-assign-btn"]',
        position: 'top',
        title: 'Chọn creative phù hợp nhất',
        text: 'Đang cập nhật assignment thật cho cả hai placement.',
      },
    },
    {
      type: 'WAIT_FOR_SELECTOR',
      target: '[data-demo="autopilot-editor-save"]:not(:disabled)',
      timeout: 30000,
      title: 'Đang kiểm tra assignment',
      text: 'Mỗi placement phải có một creative đã được duyệt trước khi lưu.',
    },
    {
      type: 'CLICK_EL',
      target: '[data-demo="autopilot-editor-save"]',
      tooltip: {
        target: '[data-demo="autopilot-editor-save"]',
        position: 'top',
        title: 'Lưu phân bổ creative',
        text: 'Đang ghi assignments, sau đó Autopilot chạy forecast, order draft và safety guard.',
      },
    },
    {
      type: 'WAIT_FOR_AUTOPILOT_TASK',
      taskKeys: ['launch_approval'],
      timeout: 180000,
      title: 'Đang chờ Duyệt launch',
      text: 'Autopilot đang hoàn tất forecast, order draft và order guard. Walkthrough sẽ dừng trước hành động tạo order.',
    },
    {
      type: 'TOOLTIP',
      target: '[data-demo="autopilot-review-artifact"][data-autopilot-task="launch_approval"]',
      position: 'top',
      title: 'Ranh giới an toàn cuối cùng',
      text: 'Audience, targeting, 2 placement, creative assignments, forecast và guard đã hội tụ vào order draft. Walkthrough **không bấm “Duyệt & tạo order”**; quyết định launch luôn thuộc về bạn.',
    },
  ]
}
