const creativeDirection = brief => [
  `Giữ ${brief.briefPatch.brand} là thương hiệu chính.`,
  'Bố cục rõ, ít chữ, hình ảnh nổi bật và phù hợp nhóm khách hàng trong brief.',
  'Không tự thêm giá, ưu đãi hoặc claim chưa có trong brief.',
].join(' ')

export function buildAutopilotLiveSteps(brief) {
  return [
    {
      type: 'TOOLTIP',
      target: '#chat-input',
      position: 'top',
      title: 'Bắt đầu bằng một scenario brief thật',
      text: `Walkthrough chọn scenario **${brief.briefPatch.brand}** từ danh sách brief mẫu. Brief sẽ được gửi qua OpenAI Campaign Agent và lưu vào canonical workspace trước khi Autopilot chạy.`,
    },
    {
      type: 'TYPE_AND_SEND',
      text: brief.chatMessage,
      tooltip: {
        target: '#chat-input',
        position: 'top',
        title: 'Đang gửi brief qua OpenAI',
        text: 'Agent đang hiểu yêu cầu, chuẩn hóa dữ liệu và tạo đề xuất cập nhật Brief.',
      },
    },
    {
      type: 'WAIT_FOR_RESPONSE',
      tooltip: {
        target: '[data-demo="chat-thread"]',
        position: 'right',
        title: 'Đang chuẩn hóa brief',
        text: 'Walkthrough chờ phản hồi thật từ model, không chèn dữ liệu giả vào run.',
      },
    },
    {
      type: 'HIGHLIGHT_MSG',
      position: 'right',
      title: 'Review đề xuất trước khi chạy',
      text: 'Đây là Brief mà Agent hiểu từ nội dung vừa gửi. Walkthrough sẽ áp dụng đề xuất này vào workspace; run Autopilot vẫn chưa bắt đầu.',
    },
    {
      type: 'APPLY_AUTOPILOT_BRIEF',
      target: '[data-demo="workspace-proposal-confirm"][data-workspace-field="brief"]',
      tooltip: {
        target: '[data-demo="chat-thread"]',
        position: 'right',
        title: 'Áp dụng Brief vào campaign truth',
        text: 'Đang xác nhận proposal và đợi backend ghi Brief vào canonical workspace.',
      },
    },
    {
      type: 'WAIT_FOR_SELECTOR',
      target: '[data-demo="autopilot-brief-status"][data-ready="true"]',
      timeout: 30000,
      title: 'Đang đồng bộ Brief',
      text: 'Autopilot chỉ mở run khi Brief đã được lưu, hợp lệ và không còn proposal chờ xử lý.',
    },
    {
      type: 'CLICK_EL',
      target: '[data-demo="autopilot-source-ai"]',
      tooltip: {
        target: '[data-demo="autopilot-source-ai"]',
        position: 'bottom',
        title: 'Chọn AI tự tạo creative',
        text: 'Run này dùng GPT Image 2 để tạo draft theo format của placement. Mỗi output vẫn đi qua quota dùng chung và Creative Intelligence.',
      },
    },
    {
      type: 'TYPE_INPUT',
      target: '[data-demo="autopilot-creative-direction"]',
      inputText: creativeDirection(brief),
      charDelay: 8,
      autoAdvance: true,
    },
    {
      type: 'CLICK_EL',
      target: '[data-demo="autopilot-policy-critical_only"]',
      tooltip: {
        target: '[data-demo="autopilot-policy-critical_only"]',
        position: 'bottom',
        title: 'Giữ quyền kiểm soát ở các bước quan trọng',
        text: 'Policy này dừng tại **Tìm audience → Thiết lập targeting → Đề xuất placement sơ bộ → Gán creative → Duyệt launch**. Creative có rủi ro vẫn luôn dừng riêng để review.',
      },
    },
    {
      type: 'TOOLTIP',
      target: '[data-demo="autopilot-start-run"]',
      position: 'top',
      title: 'Khởi tạo durable run',
      text: 'Sau khi bấm, backend tạo một plan có task, dependency, evidence và idempotency riêng. Walkthrough sẽ chờ từng checkpoint thật thay vì chạy theo timer cố định.',
    },
    {
      type: 'CLICK_EL',
      target: '[data-demo="autopilot-start-run"]',
      tooltip: {
        target: '[data-demo="autopilot-start-run"]',
        position: 'top',
        title: 'Autopilot đang lập kế hoạch',
        text: 'Đang tạo run và thực thi các bước đầu tiên.',
      },
    },
    {
      type: 'WAIT_FOR_AUTOPILOT_TASK',
      taskKeys: ['retrieve_audience'],
      timeout: 120000,
      title: 'Đang chờ checkpoint Tìm audience',
      text: 'Agent đang dùng brief, catalog và retrieval pipeline để chọn tập audience ban đầu.',
    },
    {
      type: 'TOOLTIP',
      target: '[data-demo="autopilot-review-artifact"][data-autopilot-task="retrieve_audience"]',
      position: 'top',
      title: 'Artifact Audience có bằng chứng',
      text: 'Thẻ này cho biết catalog đã được tìm như thế nào, số ứng viên RAG và các segment cuối cùng. Ta sẽ mở editor và giữ lại ít segment hơn.',
    },
    {
      type: 'CLICK_EL',
      target: '[data-demo="autopilot-edit-retrieve_audience"]',
      tooltip: {
        target: '[data-demo="autopilot-edit-retrieve_audience"]',
        position: 'top',
        title: 'Chỉnh Audience trong cùng run',
        text: 'Editor dùng canonical workspace. Khi lưu, Autopilot chỉ tính lại nhánh phụ thuộc; các artifact không liên quan được giữ nguyên.',
      },
    },
    {
      type: 'WAIT_FOR_SELECTOR',
      target: '[data-demo="autopilot-audience-option"][aria-pressed="true"]',
      timeout: 30000,
      title: 'Đang mở danh sách segment',
      text: 'Walkthrough chờ catalog và lựa chọn hiện tại hiển thị đầy đủ.',
    },
    {
      type: 'TRIM_AUTOPILOT_AUDIENCE',
      keep: 3,
      title: 'Giảm audience xuống 3 segment',
      text: 'Walkthrough đang bỏ bớt các segment cuối danh sách và giữ ba lựa chọn đầu tiên để minh họa quyền chỉnh quyết định của Agent.',
    },
    {
      type: 'TOOLTIP',
      target: '[data-demo="ai-reco-section"]',
      position: 'top',
      title: 'Audience đã được thu gọn',
      text: 'Các card được bỏ chọn ngay trên form thật. Unique reach sẽ được backend tính lại cho tập segment mới.',
    },
    {
      type: 'WAIT_FOR_SELECTOR',
      target: '[data-demo="autopilot-editor-save"]:not(:disabled)',
      timeout: 30000,
      title: 'Đang tính lại unique reach',
      text: 'Nút lưu chỉ mở khi tập audience mới có dữ liệu hợp lệ.',
    },
    {
      type: 'CLICK_EL',
      target: '[data-demo="autopilot-editor-save"]',
      tooltip: {
        target: '[data-demo="autopilot-editor-save"]',
        position: 'top',
        title: 'Lưu Audience và replan',
        text: 'Đang ghi artifact Audience mới. Review đang chờ sẽ được supersede an toàn và run tiếp tục từ dependency phù hợp.',
      },
    },
    {
      type: 'WAIT_FOR_AUTOPILOT_TASK',
      taskKeys: ['derive_targeting'],
      timeout: 120000,
      title: 'Đang chờ checkpoint Thiết lập targeting',
      text: 'Agent đang suy ra targeting từ brief và audience vừa được chỉnh.',
    },
    {
      type: 'TOOLTIP',
      target: '[data-demo="autopilot-review-artifact"][data-autopilot-task="derive_targeting"]',
      position: 'top',
      title: 'Targeting là artifact riêng',
      text: 'Tuổi, giới tính, địa lý và device được lưu độc lập với DMP segments. Vì vậy ta có thể đổi targeting mà không ghi đè Audience.',
    },
    {
      type: 'CLICK_EL',
      target: '[data-demo="autopilot-edit-derive_targeting"]',
      tooltip: {
        target: '[data-demo="autopilot-edit-derive_targeting"]',
        position: 'top',
        title: 'Mở targeting catalog',
        text: 'Walkthrough sẽ thêm lựa chọn hợp lệ từ catalog thay vì tự tạo chuỗi targeting.',
      },
    },
    {
      type: 'WAIT_FOR_SELECTOR',
      target: '[data-demo="autopilot-targeting-option"][data-targeting-dimension="age"]',
      timeout: 30000,
      title: 'Đang tải targeting options',
      text: 'Chờ các giá trị hợp lệ từ targeting catalog.',
    },
    {
      type: 'CHANGE_AUTOPILOT_TARGETING',
      dimensions: ['age', 'deviceOS'],
      title: 'Thử một cấu hình targeting khác',
      text: 'Walkthrough đang thêm một nhóm tuổi và một hệ điều hành chưa được chọn. Đây là thay đổi thật trên form và vẫn bị giới hạn bởi catalog.',
    },
    {
      type: 'TOOLTIP',
      target: '[data-demo="targeting-panel-toggle"]',
      position: 'top',
      title: 'Targeting đã thay đổi',
      text: 'Badge tổng số lựa chọn đã cập nhật. Khi lưu, Autopilot sẽ đánh dấu đúng các task downstream cần tính lại.',
    },
    {
      type: 'WAIT_FOR_SELECTOR',
      target: '[data-demo="autopilot-editor-save"]:not(:disabled)',
      timeout: 30000,
      title: 'Đang kiểm tra targeting',
      text: 'Chỉ các lựa chọn hợp lệ trong catalog mới có thể được lưu.',
    },
    {
      type: 'CLICK_EL',
      target: '[data-demo="autopilot-editor-save"]',
      tooltip: {
        target: '[data-demo="autopilot-editor-save"]',
        position: 'top',
        title: 'Lưu targeting và tiếp tục run',
        text: 'Đang commit targeting mới vào canonical workspace.',
      },
    },
    {
      type: 'WAIT_FOR_AUTOPILOT_TASK',
      taskKeys: ['plan_placement_intent'],
      timeout: 120000,
      title: 'Đang chờ Đề xuất placement sơ bộ',
      text: 'Autopilot đang kiểm tra inventory, conflict và xếp hạng shortlist trước khi biết creative cuối.',
    },
    {
      type: 'TOOLTIP',
      target: '[data-demo="autopilot-review-artifact"][data-autopilot-task="plan_placement_intent"]',
      position: 'top',
      title: 'Shortlist placement trước creative',
      text: 'Đây là đề xuất sơ bộ dựa trên inventory. Ta sẽ bỏ bớt cho đến khi còn đúng **2 placement**, sau đó creative format plan sẽ được tính từ hai lựa chọn này.',
    },
    {
      type: 'TRIM_AUTOPILOT_PLACEMENTS',
      keep: 2,
      title: 'Giữ lại đúng 2 placement',
      text: 'Walkthrough đang bỏ chọn từng placement trên artifact review. Thay đổi chỉ được lưu khi duyệt checkpoint.',
    },
    {
      type: 'TOOLTIP',
      target: '[data-demo="autopilot-review-artifact"][data-autopilot-task="plan_placement_intent"]',
      position: 'top',
      title: 'Hai placement đã được chọn',
      text: 'Format plan, số lượt tạo ảnh và forecast downstream sẽ dùng đúng shortlist này.',
    },
    {
      type: 'CLICK_EL',
      target: '[data-demo="autopilot-review-approve"][data-autopilot-task="plan_placement_intent"]',
      tooltip: {
        target: '[data-demo="autopilot-review-approve"]',
        position: 'top',
        title: 'Duyệt shortlist và tạo creative',
        text: 'Autopilot đang lưu 2 placement, lập format plan, tạo ảnh bằng GPT Image 2 và chạy Creative Intelligence. Bước này có thể mất vài phút.',
      },
    },
    {
      type: 'WAIT_FOR_AUTOPILOT_TASK',
      taskKeys: ['analyze_creatives', 'assign_creatives'],
      timeout: 360000,
      title: 'Đang tạo và phân tích creative',
      text: 'Walkthrough chờ task thật. Nếu Creative Intelligence yêu cầu con người review, nhánh duyệt thủ công sẽ xuất hiện trước bước gán creative.',
    },
    {
      type: 'TOOLTIP',
      target: '[data-demo="autopilot-review-artifact"][data-autopilot-task="analyze_creatives"]',
      whenAutopilotTask: 'analyze_creatives',
      position: 'top',
      title: 'Creative Intelligence yêu cầu review',
      text: 'Ít nhất một ảnh cần con người xác nhận. Walkthrough sẽ mở Creative editor, đọc trạng thái và không bỏ qua hàng rào này.',
    },
    {
      type: 'CLICK_EL',
      target: '[data-demo="autopilot-edit-analyze_creatives"]',
      whenAutopilotTask: 'analyze_creatives',
      tooltip: {
        target: '[data-demo="autopilot-edit-analyze_creatives"]',
        position: 'top',
        title: 'Mở Creative review',
        text: 'Đang mở các ảnh, verdict và lý do review từ VLM.',
      },
    },
    {
      type: 'WAIT_FOR_CREATIVE_REVIEW',
      whenAutopilotTask: 'analyze_creatives',
      reviewStates: ['ready', 'blocked'],
      timeout: 120000,
      title: 'Đang đọc kết quả Creative Intelligence',
      text: 'Walkthrough chỉ tiếp tục khi mọi ảnh có verdict cuối.',
    },
    {
      type: 'TYPE_INPUT',
      target: '#creative-manual-review-reason',
      whenAutopilotTask: 'analyze_creatives',
      whenReviewState: 'blocked',
      inputText: 'Đã kiểm tra thủ công nội dung, thương hiệu và chấp nhận sử dụng trong walkthrough Autopilot.',
      charDelay: 10,
      autoAdvance: true,
    },
    {
      type: 'CLICK_EL',
      target: '#creative-manual-review-approve',
      whenAutopilotTask: 'analyze_creatives',
      whenReviewState: 'blocked',
      tooltip: {
        target: '#creative-manual-review-approve',
        position: 'top',
        title: 'Ghi nhận duyệt thủ công',
        text: 'Lý do phê duyệt được lưu cùng verdict, không chỉ thay đổi trạng thái trên giao diện.',
      },
    },
    {
      type: 'WAIT_FOR_CREATIVE_REVIEW',
      whenAutopilotTask: 'analyze_creatives',
      reviewStates: ['ready'],
      timeout: 60000,
      title: 'Đang chờ creative sẵn sàng',
      text: 'Mọi creative phải được auto-approve hoặc có override hợp lệ.',
    },
    {
      type: 'CLICK_EL',
      target: '[data-demo="autopilot-editor-save"]',
      whenAutopilotTask: 'analyze_creatives',
      tooltip: {
        target: '[data-demo="autopilot-editor-save"]',
        position: 'top',
        title: 'Lưu verdict và quay lại run',
        text: 'Autopilot sẽ recheck nhánh creative trước khi xếp hạng placement cuối.',
      },
    },
    {
      type: 'WAIT_FOR_AUTOPILOT_TASK',
      taskKeys: ['assign_creatives'],
      timeout: 240000,
      title: 'Đang chờ checkpoint Gán creative',
      text: 'Agent đang giữ lại placement tương thích và chuẩn bị phân bổ các ảnh đã duyệt.',
    },
    {
      type: 'TOOLTIP',
      target: '[data-demo="autopilot-creative-plan"]',
      position: 'top',
      title: 'Creative được tạo theo format plan',
      text: 'Mỗi asset hiển thị format, kích thước, model và số placement có thể phủ. Đây là đầu ra thật của run, không phải ảnh demo được chèn sẵn.',
    },
    {
      type: 'CLICK_EL',
      target: '[data-demo="autopilot-edit-assign_creatives"]',
      tooltip: {
        target: '[data-demo="autopilot-edit-assign_creatives"]',
        position: 'top',
        title: 'Mở creative assignment',
        text: 'Ta sẽ để bộ chọn chấm điểm lại và gán creative đã duyệt phù hợp nhất cho từng placement.',
      },
    },
    {
      type: 'WAIT_FOR_SELECTOR',
      target: '[data-demo="autopilot-creative-assignment-editor"]',
      timeout: 30000,
      title: 'Đang mở ma trận creative × placement',
      text: 'Mỗi hàng là một placement; mỗi lựa chọn là creative đã có verdict.',
    },
    {
      type: 'TOOLTIP',
      target: '[data-demo="auto-assign-btn"]',
      position: 'top',
      title: 'Creative selection có giải thích',
      text: 'Nút này chọn file đã duyệt có điểm tương thích tốt nhất cho từng placement dựa trên format và tỷ lệ. Người vận hành vẫn có thể thay từng lựa chọn.',
    },
    {
      type: 'CLICK_EL',
      target: '[data-demo="auto-assign-btn"]',
      tooltip: {
        target: '[data-demo="auto-assign-btn"]',
        position: 'top',
        title: 'Chọn creative phù hợp nhất',
        text: 'Đang cập nhật assignment thật cho cả hai placement.',
      },
    },
    {
      type: 'WAIT_FOR_SELECTOR',
      target: '[data-demo="autopilot-editor-save"]:not(:disabled)',
      timeout: 30000,
      title: 'Đang kiểm tra assignment',
      text: 'Mỗi placement phải có một creative đã được duyệt trước khi lưu.',
    },
    {
      type: 'CLICK_EL',
      target: '[data-demo="autopilot-editor-save"]',
      tooltip: {
        target: '[data-demo="autopilot-editor-save"]',
        position: 'top',
        title: 'Lưu phân bổ creative',
        text: 'Đang ghi assignments, sau đó Autopilot chạy forecast, order draft và safety guard.',
      },
    },
    {
      type: 'WAIT_FOR_AUTOPILOT_TASK',
      taskKeys: ['launch_approval'],
      timeout: 180000,
      title: 'Đang chờ Duyệt launch',
      text: 'Autopilot đang hoàn tất forecast, order draft và order guard. Walkthrough sẽ dừng trước hành động tạo order.',
    },
    {
      type: 'TOOLTIP',
      target: '[data-demo="autopilot-review-artifact"][data-autopilot-task="launch_approval"]',
      position: 'top',
      title: 'Ranh giới an toàn cuối cùng',
      text: 'Audience, targeting, 2 placement, creative assignments, forecast và guard đã hội tụ vào order draft. Walkthrough **không bấm “Duyệt & tạo order”**; quyết định launch luôn thuộc về bạn.',
    },
  ]
}
