import { useState } from 'react'
import {
  ArrowLeft, BarChart3, Bot, CalendarDays, Download, FileText, History,
  Image, Layers3, Mail, MessageSquare, RefreshCw, ShieldCheck, Sparkles,
  Target, Wallet,
} from 'lucide-react'

const money = value => Number.isFinite(Number(value))
  ? new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND', maximumFractionDigits: 0 }).format(Number(value))
  : '—'

const tabs = [
  ['overview', 'Tổng quan'], ['setup', 'Campaign setup'], ['reports', 'Báo cáo'],
  ['agent', 'Campaign Agent'],
]

function Metric({ icon: Icon, label, value, detail, tone = 'blue' }) {
  const tones = {
    blue: 'bg-blue-50 text-blue-700', emerald: 'bg-emerald-50 text-emerald-700',
    violet: 'bg-violet-50 text-violet-700', amber: 'bg-amber-50 text-amber-700',
  }
  return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><span className={`flex h-9 w-9 items-center justify-center rounded-xl ${tones[tone]}`}><Icon className="h-5 w-5" /></span><p className="mt-4 text-xs font-bold uppercase tracking-[.12em] text-slate-400">{label}</p><p className="mt-1 text-xl font-black text-slate-950">{value}</p>{detail && <p className="mt-1 text-xs text-slate-500">{detail}</p>}</div>
}

function PlaceholderNotice() {
  return <div className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-xs leading-5 text-blue-800"><strong>Dữ liệu nối tiếp:</strong> UI này đã nằm đúng trong Agent application. Các module report chi tiết, email schedule và live evaluation sẽ dùng campaign API riêng; nội dung minh họa bên dưới không được coi là campaign truth.</div>
}

export default function CampaignManagement({ campaign, loading, onBack, onOpenHistory }) {
  const [tab, setTab] = useState('overview')
  if (loading) return <div className="flex min-h-screen items-center justify-center bg-slate-50 text-sm text-slate-500">Đang tải campaign…</div>
  if (!campaign) return <div className="flex min-h-screen items-center justify-center bg-slate-50 p-5"><div className="max-w-md rounded-2xl border border-slate-200 bg-white p-6 text-center shadow-sm"><h1 className="font-black text-slate-900">Không tìm thấy campaign</h1><p className="mt-2 text-sm text-slate-500">Campaign không tồn tại hoặc không thuộc tài khoản/thiết bị này.</p><button type="button" onClick={onBack} className="mt-4 rounded-xl bg-brand-500 px-4 py-2.5 text-sm font-black text-white">Về danh sách campaign</button></div></div>
  const order = campaign.order || {}
  const status = campaign.lifecycle === 'active' ? 'Đang vận hành' : campaign.lifecycle === 'paused' ? 'Tạm dừng' : campaign.lifecycle === 'completed' ? 'Hoàn tất' : 'Đã tạo campaign'

  return <main className="min-h-screen bg-[#eef4fb]">
    <header className="border-b border-slate-200 bg-white/95 px-4 py-3 backdrop-blur sm:px-7"><div className="mx-auto flex max-w-7xl items-center gap-3"><button type="button" onClick={onBack} className="flex h-10 w-10 items-center justify-center rounded-xl border border-slate-200 text-slate-600 hover:bg-slate-50"><ArrowLeft className="h-5 w-5" /></button><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-brand-500"><Bot className="h-5 w-5 text-white" /></span><div className="min-w-0 flex-1"><p className="truncate text-xs font-black uppercase tracking-[.16em] text-brand-600">Campaign Management</p><p className="truncate text-sm text-slate-500">Advertising Agent</p></div>{campaign.routes?.conversation && <button type="button" onClick={() => onOpenHistory(campaign)} className="hidden items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold text-slate-600 sm:flex"><History className="h-4 w-4" /> Xem flow đã hoàn tất</button>}</div></header>
    <div className="mx-auto max-w-7xl px-4 py-6 sm:px-7">
      <section className="rounded-3xl bg-gradient-to-br from-[#061a3d] via-[#0b2c5e] to-[#0c4a8c] p-6 text-white shadow-[0_24px_60px_rgba(4,26,61,.22)] sm:p-8"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full border border-emerald-300/30 bg-emerald-400/15 px-3 py-1 text-[10px] font-black tracking-[.14em] text-emerald-200">{status.toUpperCase()}</span><span className="rounded-full border border-white/15 bg-white/10 px-3 py-1 text-[10px] font-black">{campaign.experience_mode === 'autopilot' ? 'AUTOPILOT' : 'COPILOT'}</span></div><h1 className="mt-4 max-w-3xl text-2xl font-black tracking-[-.035em] sm:text-4xl">{campaign.title}</h1><p className="mt-3 text-sm text-blue-100">Campaign ID {campaign.campaign_id} · {order.order_count || 1} order đã xác minh</p></div><div className="flex flex-wrap gap-2"><button type="button" className="inline-flex items-center gap-2 rounded-xl border border-white/20 bg-white/10 px-4 py-2.5 text-xs font-black"><Download className="h-4 w-4" /> Tải báo cáo</button><button type="button" className="inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-xs font-black text-[#0b2c5e]"><Mail className="h-4 w-4" /> Thiết lập email</button></div></div></section>

      <nav className="mt-5 flex gap-1 overflow-x-auto rounded-2xl border border-slate-200 bg-white p-1.5 shadow-sm" aria-label="Campaign management tabs">{tabs.map(([value, label]) => <button key={value} type="button" onClick={() => setTab(value)} className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-xs font-black ${tab === value ? 'bg-brand-500 text-white shadow-sm' : 'text-slate-500 hover:bg-slate-50'}`}>{label}</button>)}</nav>

      {tab === 'overview' && <div className="mt-5 space-y-5"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={Wallet} label="Ngân sách" value={money(order.budget)} detail={order.daily_budget ? `${money(order.daily_budget)} / ngày` : 'Ngân sách campaign'} /><Metric icon={Layers3} label="Placement" value={order.placement_count ?? '—'} detail="Ad zones đã gán" tone="violet" /><Metric icon={Image} label="Creative" value={order.creative_count ?? '—'} detail="Asset đã duyệt" tone="emerald" /><Metric icon={ShieldCheck} label="Cảnh báo" value={order.warning_count ?? 0} detail="Cần theo dõi" tone="amber" /></div><div className="grid gap-5 lg:grid-cols-[1.4fr_.6fr]"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.14em] text-brand-600">Delivery pulse</p><h2 className="mt-1 text-lg font-black text-slate-950">Tình trạng campaign</h2></div><RefreshCw className="h-5 w-5 text-slate-400" /></div><PlaceholderNotice /><div className="mt-5 grid h-48 grid-cols-8 items-end gap-3 rounded-xl border border-dashed border-slate-200 bg-slate-50 p-5">{[42,58,51,68,73,66,82,76].map((height, index) => <div key={index} className="rounded-t-md bg-gradient-to-t from-brand-600 to-brand-400" style={{ height: `${height}%` }} />)}</div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[.14em] text-violet-600">Agent focus</p><h2 className="mt-1 text-lg font-black text-slate-950">Việc cần chú ý</h2><div className="mt-4 space-y-3">{['Theo dõi pacing so với ngân sách', 'Kiểm tra creative fatigue', 'Đánh giá lại placement hiệu suất thấp'].map((text, index) => <div key={text} className="flex gap-3 rounded-xl bg-slate-50 p-3"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-violet-100 text-xs font-black text-violet-700">{index + 1}</span><p className="text-xs font-semibold leading-5 text-slate-700">{text}</p></div>)}</div></section></div></div>}

      {tab === 'setup' && <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_1fr]"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[.14em] text-brand-600">Campaign truth</p><h2 className="mt-1 text-lg font-black text-slate-950">Thiết lập đã launch</h2><dl className="mt-5 divide-y divide-slate-100 text-sm">{[['Mục tiêu', order.objective || '—'], ['Ngân sách', money(order.budget)], ['Ngân sách ngày', money(order.daily_budget)], ['Ngày bắt đầu', order.start_date || '—'], ['Ngày kết thúc', order.end_date || '—'], ['Trạng thái order', order.status || '—']].map(([label, value]) => <div key={label} className="grid grid-cols-[140px_1fr] gap-4 py-3"><dt className="text-slate-500">{label}</dt><dd className="font-bold text-slate-900">{value}</dd></div>)}</dl></section><section className="space-y-4"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><Target className="h-6 w-6 text-brand-600" /><h3 className="mt-3 font-black text-slate-900">Placement & targeting</h3><p className="mt-2 text-sm leading-6 text-slate-500">{order.placement_count || 0} placement đã được gắn với campaign. Detail API sẽ cung cấp tên zone, format, targeting và assignment.</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><CalendarDays className="h-6 w-6 text-violet-600" /><h3 className="mt-3 font-black text-slate-900">Lịch vận hành</h3><p className="mt-2 text-sm leading-6 text-slate-500">Live evaluation và lịch gửi báo cáo sẽ xuất hiện tại đây mà không thay đổi campaign truth.</p></div></section></div>}

      {tab === 'reports' && <div className="mt-5 space-y-5"><PlaceholderNotice /><div className="grid gap-5 lg:grid-cols-[1.3fr_.7fr]"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><BarChart3 className="h-6 w-6 text-brand-600" /><div><h2 className="font-black text-slate-950">Campaign Performance — Daily Combo</h2><p className="text-xs text-slate-500">Impressions, clicks và CTR theo ngày</p></div></div><div className="mt-6 flex h-64 items-end gap-3 border-b border-l border-slate-200 px-4">{[48,72,60,57,78,75,64,67].map((height, index) => <div key={index} className="flex flex-1 flex-col items-center justify-end"><div className="w-full rounded-t bg-brand-500" style={{ height: `${height}%` }} /><span className="mt-2 text-[9px] text-slate-400">D{index + 1}</span></div>)}</div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><FileText className="h-6 w-6 text-emerald-600" /><h2 className="mt-3 font-black text-slate-950">Report workflow</h2><div className="mt-4 space-y-3">{['Setup report', 'Daily Ops', 'Awareness', 'Consideration', 'Conversion', 'Executive'].map((value, index) => <div key={value} className="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-2.5 text-xs"><span className="font-bold text-slate-700">{value}</span><span className={index < 2 ? 'text-emerald-600' : 'text-slate-400'}>{index < 2 ? 'Sẵn sàng' : 'Chờ dữ liệu'}</span></div>)}</div></section></div></div>}

      {tab === 'agent' && <div className="mt-5 grid gap-5 lg:grid-cols-[.65fr_1.35fr]"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><Sparkles className="h-6 w-6 text-violet-600" /><h2 className="mt-3 text-lg font-black text-slate-950">Campaign Agent</h2><p className="mt-2 text-sm leading-6 text-slate-500">Hỏi về trạng thái campaign, yêu cầu phân tích hoặc chuẩn bị hành động. Mọi thay đổi vẫn cần proposal và quyền duyệt phù hợp.</p></section><section className="flex min-h-[420px] flex-col rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-4"><p className="text-sm font-black text-slate-900">Chat về campaign hiện tại</p><p className="mt-1 text-xs text-slate-500">Không chỉnh flow lịch sử; Agent làm việc trên campaign management context.</p></div><div className="flex flex-1 items-center justify-center p-8 text-center"><div><MessageSquare className="mx-auto h-9 w-9 text-brand-300" /><p className="mt-3 text-sm font-bold text-slate-700">Campaign chat sẽ được nối ở phase tiếp theo</p><p className="mt-1 text-xs text-slate-500">UI placeholder — chưa gửi dữ liệu hoặc thực hiện action.</p></div></div><div className="border-t border-slate-100 p-3"><div className="flex items-center rounded-xl bg-slate-100 px-4 py-3 text-sm text-slate-400">Hỏi Agent về campaign…</div></div></section></div>}
    </div>
  </main>
}
