"""
Order API wrappers — POST/GET /api/orders
Real schema confirmed from live API data.
"""
import httpx
from datetime import date
from config import config
from request_context import get_request_id

_client = httpx.AsyncClient(base_url=config.BACKEND_URL, timeout=15.0)


def _correlation_headers() -> dict[str, str]:
    request_id = get_request_id()
    return {"X-Request-Id": request_id} if request_id != "-" else {}


async def create_order(payload: dict) -> dict:
    """
    POST /api/orders — creates a single campaign order (all zones in one).

    Idempotency (Phase 0): payload SHOULD carry `idempotencyKey` (uuid4 from the
    frontend confirm click, or generated by the caller). On timeout/5xx we retry
    ONCE with the same key — the backend dedupes, so a commit-then-timeout can
    never double-book. Retry without the same key is forbidden.
    """
    last_err: Exception | None = None
    for attempt in (1, 2):
        try:
            resp = await _client.post(
                "/api/orders", json=payload, headers=_correlation_headers()
            )
            if resp.status_code == 409:
                return {"error": "conflict", "detail": resp.json()}
            resp.raise_for_status()
            return resp.json()
        except (httpx.TimeoutException, httpx.HTTPStatusError) as e:
            retryable = isinstance(e, httpx.TimeoutException) or (
                isinstance(e, httpx.HTTPStatusError) and e.response.status_code >= 500
            )
            if not retryable or attempt == 2 or not payload.get("idempotencyKey"):
                raise
            last_err = e  # retry once, same idempotencyKey
    raise last_err  # unreachable, keeps type-checkers happy


async def fetch_order(order_id: str) -> dict:
    """GET /api/orders/:id"""
    resp = await _client.get(
        f"/api/orders/{order_id}", headers=_correlation_headers()
    )
    resp.raise_for_status()
    return resp.json()


async def fetch_all_orders() -> list[dict]:
    """GET /api/orders"""
    resp = await _client.get("/api/orders", headers=_correlation_headers())
    resp.raise_for_status()
    return resp.json()


async def fetch_zone_conflicts(start_date: str, end_date: str) -> dict[str, dict]:
    """
    Returns a dict { zone_id: { orderId, campaignName, startDate, endDate } }
    for all zones that are already booked by an active order whose date range
    overlaps with [start_date, end_date].

    Overlap condition: start1 <= end2 AND start2 <= end1
    """
    if not start_date or not end_date:
        return {}

    try:
        orders = await fetch_all_orders()
    except Exception:
        return {}  # Non-critical — don't block zone fetch on failure

    # Normalize to date objects for comparison
    def parse(d: str) -> date | None:
        try:
            return date.fromisoformat(d[:10])
        except Exception:
            return None

    camp_start = parse(start_date)
    camp_end = parse(end_date)
    if not camp_start or not camp_end:
        return {}

    conflicts: dict[str, dict] = {}
    skip_statuses = {"archived", "cancelled", "deleted"}

    for order in orders:
        status = (order.get("status") or "").lower()
        if status in skip_statuses:
            continue

        o_start = parse(order.get("startDate") or order.get("start_date") or "")
        o_end   = parse(order.get("endDate")   or order.get("end_date")   or "")
        if not o_start or not o_end:
            continue

        # Check overlap
        if camp_start <= o_end and o_start <= camp_end:
            placements = order.get("placements") or []
            order_id = order.get("id") or order.get("_id") or "?"
            campaign_name = order.get("brand") or order.get("name") or order_id
            for zone_id in placements:
                if zone_id not in conflicts:  # First conflict wins
                    conflicts[zone_id] = {
                        "orderId": order_id,
                        "campaignName": campaign_name,
                        "startDate": str(o_start),
                        "endDate": str(o_end),
                        "idempotencyKey": order.get("idempotencyKey", ""),
                    }

    return conflicts
