"""
Pydantic models — request/response contracts for POST /api/agent/chat.
Matches agentApi.js frontend payload exactly.
"""
from __future__ import annotations
from typing import Any
from pydantic import BaseModel, Field, field_validator

from brief_dates import normalize_brief_date


# ── Inbound: form data sub-models ────────────────────────────────────────────

class BriefData(BaseModel):
    brand: str = Field(default="", max_length=200)
    advertiser: str = Field(default="", max_length=200)
    objective: str = Field(default="awareness", max_length=32)
    kpi: str = Field(default="", max_length=500)
    budget: float = Field(default=0, ge=0, le=5000)  # triệu VND
    startDate: str = Field(default="", max_length=64)
    endDate: str = Field(default="", max_length=64)
    notes: str = Field(default="", max_length=12000)

    @field_validator("startDate", "endDate", mode="before")
    @classmethod
    def normalize_campaign_dates(cls, value):
        return normalize_brief_date(value)


class CreativeFile(BaseModel):
    id: str = Field(default="", max_length=200)
    name: str = Field(default="", max_length=500)
    type: str = Field(default="", max_length=100)
    size: int = Field(default=0, ge=0, le=20 * 1024 * 1024)
    width: int = Field(default=0, ge=0, le=20000)
    height: int = Field(default=0, ge=0, le=20000)
    url: str = Field(default="", max_length=2048)
    analysisId: str = Field(default="", max_length=200)
    analysisStatus: str = Field(default="", max_length=100)
    reviewReasons: list[str] = Field(default_factory=list, max_length=30)
    deterministic: dict = Field(default_factory=dict)
    vlm: dict = Field(default_factory=dict)
    override: dict = Field(default_factory=dict)
    formatId: str = Field(default="", max_length=100)
    intendedFormat: str = Field(default="", max_length=100)
    source: str = Field(default="", max_length=100)
    derivedFromFileId: str = Field(default="", max_length=200)
    repairMethod: str = Field(default="", max_length=32)


class CreativeData(BaseModel):
    files: list[CreativeFile] = Field(default_factory=list, max_length=20)


class SegmentAttr(BaseModel):
    _id: str = ""                  # MongoDB ObjectId — used in dmp.include[]
    segmentId: str = ""
    type: str = ""
    category: str = ""
    name: str = ""
    fullLabel: str = ""
    sizeMin: int | None = None
    sizeMax: int | None = None

    model_config = {"populate_by_name": True, "extra": "allow"}


class SegmentData(BaseModel):
    attrs: list[dict] = Field(default_factory=list, max_length=100)
    size: int = Field(default=0, ge=0)
    targeting: dict[str, list] = Field(default_factory=dict)


class SetupData(BaseModel):
    phase: int = 0                 # 0=zone recommend, 1=creative match, 2=order create
    selectedZoneIds: list[str] = Field(default_factory=list, max_length=100)
    assignments: dict[str, int] = Field(default_factory=dict)
    targeting: dict[str, list] = Field(default_factory=dict)
    regenerate: bool = False
    fileUrls: dict[str, str] = Field(default_factory=dict)
    # Phase 0 idempotency: uuid4 generated by the frontend on the confirm click.
    # Same key on user retry of the same confirm → backend dedupes the order.
    idempotencyKey: str = ""


class FormData(BaseModel):
    brief: BriefData | None = None
    creative: CreativeData | None = None
    segment: SegmentData | None = None
    setup: SetupData | None = None


# ── Inbound: main chat request ────────────────────────────────────────────────

class ChatRequest(BaseModel):
    session_id: str = Field(
        default="default", min_length=1, max_length=128,
        pattern=r"^[A-Za-z0-9_.:-]+$",
    )
    step: int = Field(default=-1, ge=-1, le=6)
    message: str = Field(default="", max_length=12000)
    experience_mode: str | None = Field(
        default=None, pattern=r"^(guided|autopilot)$"
    )
    formData: FormData | None = None
    workspace: dict | None = None          # Live formState from frontend (compact, no dataUrls)
    workspace_revision: int | None = None  # Optimistic-concurrency revision of that snapshot
    confirmed_steps: list[int] | None = Field(default=None, max_length=10)
    workspace_events: list[str] | None = Field(default=None, max_length=50)


# ── Outbound: agent response ──────────────────────────────────────────────────

class ResponseMeta(BaseModel):
    tool: str | None = None        # Which tool/handler ran
    model: str = "none"            # "minimax" | "none"
    step: int = -1


class Block(BaseModel):
    """
    Rich UI block. Types:
    - table:              { title, columns[], rows[][] }
    - info:               { text }
    - campaign_list:      { campaigns[] }
    - audience_size:      { size, breakdown[] }
    - metric_grid:        { metrics[] }
    - workspace_proposal: { changes: {field, value, reason}, is_locked, warning }
    """
    type: str
    model_config = {"extra": "allow"}


class AgentResponse(BaseModel):
    text: str = ""
    blocks: list[dict] = []
    meta: ResponseMeta | dict = {}
    workspace_update: dict | None = None   # Patch to apply to formState after user confirms
    suggestions: list = []           # Quick-reply chips — strings or {label, action, text}
    # Channel-only rich parts. Web clients may ignore these; Zalo uses them to
    # deliver review images without invoking a second model/tool loop.
    media_parts: list[dict] = []
