global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: agent
    metrics_path: /metrics
    static_configs:
      - targets: ["agent:8080"]
        labels:
          environment: production
  - job_name: advertising-agent-hackathon
    scheme: https
    metrics_path: /agent/metrics
    static_configs:
      - targets: ["zah-4.123c.vn:443"]
        labels:
          environment: hackathon
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
